Repository Americastestkitchen/mise-ui, pull requests merged in 2021-12, with the labels that each got.

#564 adding crossOrigin and decoding attrs where missing
  package.json
  src/components/Ads/ReviewsAds/CookingSchoolAd/index.js
  src/components/Ads/ReviewsAds/ReviewsMarketingHat/index.js
  src/components/Ads/ShowcaseAds/FreeTrialAd/index.js
  src/components/Ads/ShowcaseAds/SingleProductShowcaseAd/index.js
  src/components/Ads/SingleProductAd/index.js
  src/components/Articles/ArticleImage/index.js
  src/components/Articles/ArticlePhotoCollection/index.js
  src/components/Articles/ImageList/ImageListItem/index.js
  src/components/Articles/SidebarCard/index.js
  src/components/Cards/SuggestionCard/components/LoadingSuggestionCard.js
  src/components/Cards/shared/Image/index.js
  src/components/DesignTokens/Brands/Amazon.js
  src/components/DesignTokens/Brands/BlueApron.js
  src/components/DesignTokens/Brands/Houzz.js
  src/components/DesignTokens/Brands/KingArthur.js
  src/components/DesignTokens/Brands/SurLaTable.js
  src/components/DesignTokens/Brands/ThermoWorks.js
  src/components/DesignTokens/Brands/Victorinox.js
  src/components/DesignTokens/Brands/WilliamsSonoma.js
  src/components/DesignTokens/Logo/svgs/GearHeads.js
  src/components/DesignTokens/Logo/svgs/MysteryRecipe.js
  src/components/DesignTokens/Logo/svgs/Proof.js
  src/components/DesignTokens/TextDecoration/svgs/CircleFive.js
  src/components/DesignTokens/TextDecoration/svgs/CircleFour.js
  src/components/DesignTokens/TextDecoration/svgs/CircleOne.js
  src/components/DesignTokens/TextDecoration/svgs/CircleThree.js
  src/components/DesignTokens/TextDecoration/svgs/CircleTwo.js
  src/components/DesignTokens/TextDecoration/svgs/SquiggleOne.js
  src/components/DesignTokens/TextDecoration/svgs/SquiggleTwo.js
  src/components/DesignTokens/TextDecoration/svgs/UnderlineOne.js
  src/components/DesignTokens/TextDecoration/svgs/UnderlineThree.js
  src/components/DesignTokens/TextDecoration/svgs/UnderlineTwo.js
  src/components/Gif/index.js
  src/components/SubscribeBubbles/logos/Stitcher.js
Labels: patch

#567 ARCHIE-3038
  src/components/Ads/ReviewsAds/ReviewsEmailCapture/ReviewsEmailCapture.stories.js
  src/components/Newsletters/InlineNewsletter/index.js
Labels: patch

#565 ARCHIE-3052
  .eslintrc
  package.json
  src/components/Buttons/Button/index.tsx
  src/components/BylineList/BylineList.stories.tsx
  src/components/BylineList/BylineList.tsx
  src/components/BylineList/index.ts
  src/components/Cards/RelatedContentCard/RelatedContentCard.stories.tsx
  src/components/Carousels/PhotoCarousel/PhotoCarousel.stories.tsx
  src/config/shared.stories.ts
  src/index.d.ts
  src/index.js
  src/styles/breakpoints.js
  src/styles/breakpoints.ts
  yarn.lock
Labels: minor

#569 cleanup set storybook calls
  src/components/BylineList/BylineList.stories.tsx
  src/components/Cards/RelatedContentCard/RelatedContentCard.stories.tsx
  src/components/Carousels/PhotoCarousel/PhotoCarousel.stories.tsx
  src/config/shared.stories.ts
Labels: patch

#570 ARCHIE 3029
  src/components/BylineList/BylineList.stories.tsx
  src/components/BylineList/BylineList.tsx
  src/components/BylineList/exampleAuthorsProp.stories.ts
  src/components/Cards/LeadMarqueeCard/LeadMarqueeCard.stories.js
  src/components/Cards/LeadMarqueeCard/LeadMarqueeCard.tsx
  src/components/Cards/LeadMarqueeCard/index.ts
Labels: patch

#572 ARCHIE-1980: Clickable bylines
  src/components/BylineList/BylineList.stories.tsx
  src/components/BylineList/BylineList.tsx
  src/components/BylineList/exampleAuthorsProp.stories.ts
  src/components/Cards/RelatedContentCard/RelatedContentCard.tsx
  src/styles/index.js
  src/styles/mixins.js
Labels: minor

#568 visual updates to SuggestionCard
  src/components/Cards/SuggestionCard/components/SuggestionCardDek.js
  src/components/Cards/SuggestionCard/index.js
Labels: patch, release

#574 ARCHIE-3040: Table of Contents
  package.json
  src/components/BylineList/BylineList.tsx
  src/components/TableOfContents/TableOfContents.stories.tsx
  src/components/TableOfContents/TableOfContents.tsx
  src/styles/index.js
  src/styles/mixins.js
  src/styles/ux-utilities.js
  yarn.lock
Labels: minor

#573 ARCHIE-3036: Media Embeds
  src/components/MediaEmbed/MediaEmbed.stories.tsx
  src/components/MediaEmbed/MediaEmbed.tsx
  src/components/MediaEmbed/index.ts
  src/components/MediaEmbed/utilities.ts
  src/index.d.ts
  src/index.js
Labels: minor

#575 ARCHIE-3040 scroll fix
  src/components/TableOfContents/index.ts
  src/index.js
  src/styles/ux-utilities.js
Labels: patch

#576 Release 1.24.1
  package.json
Labels: patch, release

#578 updating BookCarouselAd to render 2022 book
  src/components/Ads/ReviewsAds/BookCarouselAd/__tests__/BookCarouselAd.spec.js
  src/components/Ads/ReviewsAds/BookCarouselAd/index.js
Labels: minor, release
