Repository Americastestkitchen/mise-ui, pull requests merged in 2021-02, with the labels that each got.

#345 Feature atk home anon
  package-lock.json
  package.json
  src/components/Accordion/index.js
  src/components/Carousels/Carousel/index.js
  src/components/DesignTokens/Icon/svgs/Plus.js
Labels: minor, patch, release

#348 this commit is being used to launch a release for mise-ui
  src/components/Accordion/index.js
Labels: patch, release

#350 updating yarn.lock and ignoring package-lock.json
  .gitignore
  package-lock.json
  yarn.lock
Labels: patch, release

#354 swap image prop to url to move image logic out of mise
  src/components/Cards/LeadMarqueeCard/LeadMarqueeCard.stories.js
  src/components/Cards/LeadMarqueeCard/__tests__/LeadMarqueeCard.spec.js
  src/components/Cards/LeadMarqueeCard/index.js
  src/components/Cards/MarqueeCard/MarqueeCard.stories.js
  src/components/Cards/MarqueeCard/__tests__/MarqueeCard.spec.js
  src/components/Cards/MarqueeCard/index.js
Labels: patch, release

#356 ARCHIE-1987 allow stickers to parse html entities
  src/components/Cards/shared/Sticker/index.js
Labels: patch, release

#355 ARCHIE-1917 add doc data attributes to standard card
  package.json
  src/components/Cards/CardWrapper/index.js
  src/components/Cards/FeatureCard/index.js
  src/components/Cards/StandardCard/index.js
Labels: patch, release

#359 exclude plyr from local build
  .babelrc
  package-lock.json
  package.json
  src/components/AudioPlayer/index.js
  src/components/Badge/__tests__/__snapshots__/Badge.spec.js.snap
  src/components/SubscribeBubbles/__tests__/SubscribeBubbles.spec.js
  src/lib/utils.js
  yarn.lock
Labels: minor, release
