Repository Americastestkitchen/mise-ui, pull requests merged in 2022-01, with the labels that each got.

#560 dollar offer updates to MarketingHat
  src/components/MarketingHat/components/HeroHatBody.js
  src/components/MarketingHat/components/HeroHatContent.js
  src/components/MarketingHat/components/HeroHatDescription.js
  src/components/MarketingHat/components/HeroHatHeading.js
  src/components/MarketingHat/components/HeroHatWrapper.js
  src/components/MarketingHat/components/RegistrantSubmit.js
  src/styles/colors.js
Labels: patch, release

#594 hs articles r4
  src/components/Cards/RelatedContentCard/RelatedContentCard.tsx
  src/components/Carousels/PhotoCarousel/PhotoCarousel.tsx
  src/components/MediaEmbed/MediaEmbed.stories.tsx
  src/components/MediaEmbed/MediaEmbed.tsx
  src/components/TableOfContents/TableOfContents.tsx
  src/styles/colors.js
  src/styles/mixins.js
Labels: patch

#595 hs articles r5
  package.json
  src/components/Articles/ArticleTextBlock/index.js
  src/components/Carousels/PhotoCarousel/PhotoCarousel.tsx
  src/components/MediaEmbed/MediaEmbed.stories.tsx
  src/components/MediaEmbed/MediaEmbed.tsx
Labels: patch

#559 reviews marketing hat
  src/components/Ads/ReviewsAds/ReviewsMarketingHat/ReviewsMarketingHat.stories.js
  src/components/Ads/ReviewsAds/ReviewsMarketingHat/index.js
  src/components/MarketingHat/index.js
Labels: patch, release

#606 changing link underline color
  src/styles/mixins.js
Labels: patch, release

#607 v1.30.0 [skip ci]
  package.json
Labels: skip-release

#605 update url for byline
  src/components/BylineList/BylineList.tsx
Labels: minor, release
