Repository Americastestkitchen/mise-ui, pull requests merged in 2022-02, with the labels that each got.

#577 Articles Detail Espresso
  package.json
  src/components/Ads/ReviewsAds/ReviewsEmailCapture/ReviewsEmailCapture.stories.js
  src/components/Ads/ReviewsAds/ReviewsEmailCapture/index.js
  src/components/Articles/ArticleTextBlock/index.js
  src/components/Articles/ImageList/ImageListContainer/ImageListContainer.stories.js
  src/components/Articles/ImageList/ImageListContainer/index.js
  src/components/Articles/ImageList/ImageListItem/index.js
  src/components/Articles/LinkFarm/LinkFarm.stories.tsx
  src/components/Articles/LinkFarm/LinkFarm.tsx
  src/components/Articles/LinkFarm/index.tsx
  src/components/Articles/SidebarCard/index.js
  src/components/BylineList/BylineList.tsx
  src/components/Cards/RelatedContentCard/RelatedContentCard.stories.tsx
  src/components/Cards/RelatedContentCard/RelatedContentCard.tsx
  src/components/Carousels/BaseCarousel/ArrowButton.tsx
  src/components/Carousels/BaseCarousel/BaseCarousel.stories.tsx
  src/components/Carousels/BaseCarousel/BaseCarousel.tsx
  src/components/Carousels/BaseCarousel/Cells/PhotoCarouselCell.tsx
  src/components/Carousels/BaseCarousel/Cells/index.tsx
  src/components/Carousels/BaseCarousel/Headers.tsx
  src/components/Carousels/BaseCarousel/Slides.tsx
  src/components/Carousels/BaseCarousel/Wrappers.tsx
  src/components/Carousels/BaseCarousel/bug-fixes.ts
  src/components/Carousels/BaseCarousel/index.tsx
  src/components/Carousels/BaseCarousel/styled-elements.tsx
  src/components/Carousels/BaseCarousel/useFlickity.ts
  src/components/Carousels/PhotoCarousel/PhotoCarousel.stories.tsx
  src/components/Carousels/PhotoCarousel/PhotoCarousel.tsx
  src/components/Carousels/PhotoCarousel/index.tsx
  src/components/MediaEmbed/Caption.tsx
  src/components/MediaEmbed/MediaEmbed.stories.tsx
  src/components/MediaEmbed/MediaEmbed.tsx
  src/components/MediaEmbed/TikTokEmbed.tsx
  src/components/MediaEmbed/utilities.ts
  src/components/TableOfContents/TableOfContents.stories.tsx
  src/components/TableOfContents/TableOfContents.tsx
  src/index.js
  src/styles/mixins.js
  yarn.lock
Labels: minor, release

#621 fixing kids newsletter font on mobile
  .gitignore
  src/components/Ads/ReviewsAds/ReviewsEmailCapture/index.js
Labels: patch, release

#625 match npm version, fix detached head issue
  .travis.yml
  package.json
Labels: skip-release

#611 Recipes Marketing Hat
  src/components/RecipesMarketingHat/RecipesMarketingHat.stories.js
  src/components/RecipesMarketingHat/__tests__/RecipesMarketingHat.spec.js
  src/components/RecipesMarketingHat/components/HeroHatBody.js
  src/components/RecipesMarketingHat/components/HeroHatContent.js
  src/components/RecipesMarketingHat/components/HeroHatDescription.js
  src/components/RecipesMarketingHat/components/HeroHatHeading.js
  src/components/RecipesMarketingHat/components/HeroHatSubHeading.js
  src/components/RecipesMarketingHat/components/HeroHatWrapper.js
  src/components/RecipesMarketingHat/components/RegistrantSubmit.js
  src/components/RecipesMarketingHat/index.js
  src/index.js
Labels: patch, release

#634 release branch for 1.33.4
  package.json
Labels: patch, release

#635 SEARCH-106: search page need visible checkbox without site key
  src/components/Algolia/shared/SortBy/SortBy.stories.js
  src/components/Algolia/shared/SortBy/index.js
Labels: patch, release

#633 Fixed Recipes Marketing Hat
  src/components/RecipesMarketingHat/components/HeroHatBody.js
Labels: patch, release

#631 Text component with a background causes font styling issues
  src/components/Articles/ArticleTextBlock/index.js
Labels: patch, release

#641 CORE-142: don't translate disabled carousel cells when its parent has display flex.
  src/components/Carousels/Carousel/index.js
Labels: patch, release

#653 deleting space
  src/components/Carousels/BaseCarousel/Cells/PhotoCarouselCell.tsx
Labels: patch, release
